### ISSUE TITLE
New EEG data set: ERP CORE

### ISSUE THREAD

**Issue by stevenjluck** [openlists/ElectrophysiologyData#3]
We have released a set of data from 40 subjects in each of 6 standard ERP paradigms, along with the stimulus presentation scripts, the data analysis scripts, and a variety of results (including data quality metrics). More details and the files are available here: https://osf.io/thsqg/

**Comment by TomDonoghue** [comment]
Thanks for the note & link, this dataset looks awesome!

I have added it to the list now, so I'm going to close this issue.
